module PagesHelper
	def home
		@details = {
      camp_id: 'MEGA-MOBILE-DEALS',
      success_url: '/success',
      form_name: 'home',
      optin_url: 'home',
      sid: "1",
      ssid: "1",
      source:'home',
      ipaddress: request.remote_ip,
    }.to_json
    @deals_list = [
      {
        image: "phones/iphone13promax.png",
        img_class: "w-50 mb-3",
        data: "Unlimited",
        title: "iPhone 13 Pro Max ",
        monthly:"36",
        button: "Continue",
        color: ["#676562","#f7f8f2","#fbe9d2","#a2c1dd"],
      },
      {
        image: "phones/galaxy-note-20-ultra.png",
        img_class: "w-77 mb-2",
        data: "Unlimited",
        title: "Galaxy Note 20 Ultra",
        monthly:"24",
        button: "Continue",
        color: ["#9a716e","#1a1815","#dad9db"],
      },
      {
        image: "phones/iphone13pro.png",
        img_class: "w-75 mb-3",
        data: "Unlimited",
        title: "iPhone 13 Pro ",
        monthly:"24",
        button: "Continue",
        color: ["#a2c1dd","#f7f8f2","#fbe9d2","#676562"],
      },
      {
        image: "phones/galaxy-note-20.png",
        img_class: "w-77 mb-2",
        data: "Unlimited",
        title: "Galaxy Note 20",
        monthly:"24",
        button: "Continue",
        color: ["#91b098","#9a716e","#545859"],
      },
      {
        image: "phones/iphone13.png",
        img_class: "w-50 mb-2",
        data: "Unlimited",
        title: "iPhone 13",
        monthly:"24",
        button: "Continue",
        color: ["#faddd7","#276787","#232a31","#faf6f2","#bf0013"],
      },
      {
        image: "phones/galaxy-s21plus.png",
        img_class: "w-50 mb-2",
        data: "Unlimited",
        title: "Samsung Galaxy S21 Plus",
        monthly:"24",
        button: "Continue",
        color: ["#dcb5b3","#211e16","#a5a8c4","#c2c9d5","#cc333d"],
      },
      {
        image: "phones/galaxy-s21ultra.png",
        img_class: "w-50 mb-2",
        data: "Unlimited",
        title: "Samsung Galaxy S21 Ultra",
        monthly:"24",
        button: "Continue",
        color: ["#c2c9d5","#211e16","#5f4e4b","#6e7074","#3a414a"],
      },
      {
        image: "phones/samsung_fold3.png",
        img_class: "w-75 mb-3",
        data: "Unlimited",
        title: "Samsung Galaxy Z Fold3 ",
        monthly:"12",
        button: "Continue",
        color: ["#cac6c4","#2d2926","#384a46"],
      },
      {
        image: "phones/galaxy-s21.png",
        img_class: "w-48 mb-3",
        data: "Unlimited",
        title: "Samsung Galaxy S21 ",
        monthly:"12",
        button: "Continue",
        color: ["#6e7074","#efc5be","#a5a8c4","#e9e9e7"],
      },
      {
        image: "phones/glaxy-zflip.png",
        img_class: "w-40 mb-3",
        data: "Unlimited",
        title: "Samsung Galaxy Z FLip3",
        monthly:"36",
        button: "Continue",
        color: ["#e3deca","#2d2926","#435551","#bfb1d2"],
      },
      {
        image: "phones/iphone12promax.png",
        img_class: "w-75 mb-3",
        data: "Unlimited",
        title: "iPhone 12 Pro Max ",
        monthly:"24",
        button: "Continue",
        color: ["#fae5c8","#2b4552","#e6e7e0","#454342"],
      },
      {
        image: "phones/iphone12pro.png",
        img_class: "w-75 mb-3",
        data: "Unlimited",
        title: "iPhone 12 Pro ",
        monthly:"24",
        button: "Continue",
        color: ["#2b4552","#fae5c8","#454342","#e6e7e0"],
      },
    ]
	end
end
